version: "3.9"
services:
  static-server:
    # static http server
    build: ../step1 # path where Dockerfile from step1 is stored
    volumes:
      - C:\Git\DAI-2022-HTTP-Infra\step1\public-html\:/usr/local/apache2/htdocs/
    labels:
      - "traefik.http.services.static-server.loadbalancer.server.port=80"
      - "traefik.http.routers.static-server.rule=PathPrefix(`/`)"
  dynamic-server:
    # dynamic http server
    build: ../step2 # path where Dockerfile from step1 is stored
    labels:
      - "traefik.http.services.dynamic-server.loadbalancer.server.port=80"
      - "traefik.http.routers.dynamic-server.rule=PathPrefix(`/api/`)"
      - "traefik.http.routers.dynamic-server.middlewares=replacepath"
      - "traefik.http.middlewares.replacepath.replacepath.path=/"
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    labels:
      - "traefik.enable=true"
    command:
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"

    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
